// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

#include <stdio.h>
#include <stdbool.h>

typedef struct {
    int x;
    int y;
} fibonacci_t;

void fibonacci_init(fibonacci_t *fib) {
    fib->x = 0;
    fib->y = 1;
}

int fibonacci_next(fibonacci_t *fib) {
    int x = fib->x;
    int y = fib->y;
    fib->x = y;
    fib->y = x + y;
    return fib->y;
}

int solve(int n) {
    int sum = 0;

    fibonacci_t fib;
    fibonacci_init(&fib);

    while (true) {
        int x = fibonacci_next(&fib);
        if (x > n) {
            break;
        }
        if (x % 2 == 0) {
            sum += x;
        }
    }
    return sum;
}

int main(void) {
    printf("RESULT = %d\n", solve(4000000));
    return 0;
}
